
name: Build Kernel

on: 
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container: ghcr.io/76op/kernel_build:main
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Get Kernel source
        run: |
          ls -la
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.82.tar.xz > /dev/null 2>&1
          tar -xvf linux-6.1.82.tar.xz > /dev/null 2>&1

      - name: Patch
        run: |
          pwd
          ls -la
          cp debian12-config linux-6.1.82/.config
          cp acso.patch linux-6.1.82/acso.patch
          cd linux-6.1.82
          patch acso.patch
          echo "$(cat drivers/pci/quirks.c | grep pcie_acs_overrides)"
          echo "-----"

      - name: Build
        run: |
          ls -la
          echo $(nproc)
          cd linux-6.1.82
          make -j$(nproc) > /dev/null 2>&1

      - name: Build DebPkg
        run: |
          make deb-pkg LOCALVERSION=-bookworm KDEB_PKGVERSION=$(make kernelversion)-1 > /dev/null 2>&1
          ls -la
          ls -la ../
